### ISSUE TITLE
[WEB-BUG] cannot login

### ISSUE THREAD

**Issue by rashgaroth** [visionplus-development/visionplus-bss-ios-sdk#15]
This issue happened when i want to watching Europe 2024, the bug was annoying. I know it's out of context, but the most annoying they don't have any feedback page that can report any issues 

https://www.awesomescreenshot.com/video/28685115

**Comment by erwindosianipar** [comment]
Hello there, thanks for reporting this issue

We are sorry for what happened to you
Please contact to ccare@visionplus.id

About feedback page we will implement that for better report

Thank you
